# Generated by Django 3.0 on 2019-12-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'In work'), (3, 'Done')], default=1),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='qrzone',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
